branch-defaults:
  default:
    environment: quizmaster-dev
    group_suffix: null
global:
  application_name: quizmaster
  branch: null
  default_ec2_keyname: itcircle
  default_platform: Python 3.6
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
